### ISSUE TITLE
Crash with Immersive Engineering

### ISSUE THREAD

**Issue by UnNinja** [BrassGoggledCoders/ModularUtilities#5]
[Crash log](http://pastebin.com/7HNt819V)

**Comment by FreneticScribbler** [comment]
I haven't been getting this issue in my dev environment. Now I have a full crash log it should help me fix it though.

**Comment by FreneticScribbler** [comment]
Cannot reproduce in development or compiled environments. Does it still occur with IE removed?

**Comment by UnNinja** [comment]
No, nor does it occur if we leave IE in and remove boilerplate/modular utilities

**Comment by FreneticScribbler** [comment]
Hmm...very strange....

**Comment by UnNinja** [comment]
Any idea on if you'll be able to fix this? I'd prefer to use both your mod and IE, but I'm sorry to say if it's a choice IE is going to win out :(

**Comment by JorVaCoding** [comment]
What version of IE, Forge, MoU, and BoilerPlate?
I'll see If I can reproduce it

**Comment by FreneticScribbler** [comment]
@UnNinja Oh don't worry, perfectly understandable that IE would win out. I'd choose the same...if I was getting the issue, which is the major problem.

@JorVaCoding The versions should be printed in the log. Thanks!

**Comment by UnNinja** [comment]
@JorVaCoding IE 0.10 - 38, Boilerplate 9.0.0, MoU 0.3.0, forge 2073

**Comment by mallrat208** [comment]
I've done some testing of this...

It seems the crash is caused by having Modular Utilities, Immersive Engineering, and Tinkers Construct.
Any of two of those won't crash together, only when all three are present.

My best guess is that it's based on load order and the double registration of a fluid.

Tinker's Construct normally registers a 'dirt' fluid just like Modular Utilities does. However with just MU and Tinkers, MU loads first preventing any issues. Once you throw IE into the mix, it requests that Tinkers loads before it leading to Tinkers to load, followed by Immersive Engineering, and then Modular Utilities.

AFAIK, forge will not allow you to register a duplicate fluid, first one to use the name gets it. It's possible that this is causing the fluid to 'fail' being created and leading to the null entry that's called as you try to create the liquid dirt bucket in the recipe creation.
